server:
  port: 9003

spring:
  application:
    name: cloudalibaba-payment-service
  cloud:
    nacos:
      discovery:
        #        server-addr: 192.168.1.104:8848 #配置nacos注册中心地址
        server-addr: 192.168.189.128:8848 #配置nacos注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
